/**
 * Bake the Bryge API key into the build.
 *
 * The plugin always talks to Bryge's own hosted API, so asking every installer to paste
 * a URL and a key was ceremony with no decision behind it. The key is injected here at
 * build time instead of being committed, so the repo never carries a live credential:
 *
 *   BRYGE_API_KEY=bk_… npm run build
 *
 * Without the env var the generated constant is empty and the setup page falls back to
 * asking, which is what a self-hosted Bryge needs anyway.
 *
 * Be clear about what this is NOT: a key baked into a frontend bundle ships to every
 * browser that loads the plugin. It is a distribution convenience, not a secret. Scope
 * the key to what a dashboard legitimately needs and rotate it without redeploying.
 */
import { writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const key = process.env.BRYGE_API_KEY ?? '';
const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'key.generated.ts');

writeFileSync(
  out,
  `// GENERATED by scripts/write-key.mjs at build time. Not committed; do not edit.\n` +
    `export const BUILT_IN_API_KEY = ${JSON.stringify(key)};\n`
);

console.log(key ? `baked in API key ${key.slice(0, 11)}…` : 'no BRYGE_API_KEY set — setup page will ask for one');
